### ISSUE TITLE
Settings feature not working in Prodigal. 

### ISSUE THREAD

**Issue by wanizubair** [SpongeBobSun/mPod#5]
#### Expected behavior

The app should be able to open settings. 

#### Actual behavior

The app is not able to open settings as settings feature does not work and we can not change our settings. 

#### How to reproduce
+ Launch the app

+ Click on the settings icon

+ The settings button does not work and you are not able to change the settings. 

* Browser: Prodigal, Version : 1.1. 0

* Operating system:Android 7.0 (Nought) 
Moto C Plus 

#### Recording Of The Bug
https://youtu.be/OW_Ersw9SBA    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/settings-feature-not-working-in-prodigal">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by SpongeBobSun** [comment]
@wanizubair Instead of clicking on the screen you should use the middle button of `clicking wheel`.
